name: fontconfig
display_name: Fontconfig
category: system
homepage: https://www.freedesktop.org/wiki/Software/fontconfig
locations:
  native:
    config: ~/.config/fontconfig
tags: [fonts, freedesktop]
